export const UPDATE_IS_BAD_TOKEN = "UPDATE_IS_BAD_TOKEN";

export const GET_INSTRUMENTS = "GET_INSTRUMENTS";
export const GET_INSTRUMENTS_SUCCEED = "GET_INSTRUMENTS_SUCCEED";
export const GET_INSTRUMENTS_FAIL = "GET_INSTRUMENTS_FAIL";

export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHERS_SUCCEED = "GET_TEACHERS_SUCCEED";
export const GET_TEACHERS_FAIL = "GET_TEACHERS_FAIL";

export const GET_TEACHERS_API = "GET_TEACHERS_API";
export const GET_TEACHERS_API_SUCCEED = "GET_TEACHERS_API_SUCCEED";
export const GET_TEACHERS_API_FAIL = "GET_TEACHERS_API_FAIL";

export const UPDATE_FILTER_TEACHERS = "UPDATE_FILTER_TEACHERS";

export const REGISTER_STUDENT_API = "REGISTER_STUDENT_API";
export const REGISTER_STUDENT_API_SUCCEED = "REGISTER_STUDENT_API_SUCCEED";
export const REGISTER_STUDENT_API_FAIL = "REGISTER_STUDENT_API_FAIL";

export const REGISTER_TEACHER_API = "REGISTER_TEACHER_API";
export const REGISTER_TEACHER_API_SUCCEED = "REGISTER_TEACHER_API_SUCCEED";
export const REGISTER_TEACHER_API_FAIL = "REGISTER_TEACHER_API_FAIL";

export const CONTACT_US_API = "CONTACT_US_API";
export const CONTACT_US_API_SUCCEED = "CONTACT_US_API_SUCCEED";
export const CONTACT_US_API_FAIL = "CONTACT_US_API_FAIL";

export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";
export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCEED = "FORGOT_PASSWORD_SUCCEED";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCEED = "RESET_PASSWORD_SUCCEED";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CHECK_PASSWORD_RESET_CODE = "CHECK_PASSWORD_RESET_CODE";
export const CHECK_PASSWORD_RESET_CODE_SUCCEED =
  "CHECK_PASSWORD_RESET_CODE_SUCCEED";
export const CHECK_PASSWORD_RESET_CODE_FAIL = "CHECK_PASSWORD_RESET_CODE_FAIL";

export const OPEN_MODAL_MESSAGE = "OPEN_MODAL_MESSAGE";
export const CLOSE_MODAL_MESSAGE = "CLOSE_MODAL_MESSAGE";

export const GET_TEACHER_PROFILE = "GET_TEACHER_PROFILE";
export const GET_TEACHER_PROFILE_SUCCEED = "GET_TEACHER_PROFILE_SUCCEED";
export const GET_TEACHER_PROFILE_FAIL = "GET_TEACHER_PROFILE_FAIL";

export const UPDATE_TEACHER_PROFILE = "UPDATE_TEACHER_PROFILE";
export const UPDATE_TEACHER_PROFILE_SUCCEED = "UPDATE_TEACHER_PROFILE_SUCCEED";
export const UPDATE_TEACHER_PROFILE_FAIL = "UPDATE_TEACHER_PROFILE_FAIL";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCEED = "UPDATE_PASSWORD_SUCCEED";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const GET_PARENT_PROFILE = "GET_PARENT_PROFILE";
export const GET_PARENT_PROFILE_SUCCEED = "GET_PARENT_PROFILE_SUCCEED";
export const GET_PARENT_PROFILE_FAIL = "GET_PARENT_PROFILE_FAIL";

export const UPDATE_PARENT_PROFILE = "UPDATE_PARENT_PROFILE";
export const UPDATE_PARENT_PROFILE_SUCCEED = "UPDATE_PARENT_PROFILE_SUCCEED";
export const UPDATE_PARENT_PROFILE_FAIL = "UPDATE_PARENT_PROFILE_FAIL";

export const GET_STUDENT_PROFILE = "GET_STUDENT_PROFILE";
export const GET_STUDENT_PROFILE_SUCCEED = "GET_STUDENT_PROFILE_SUCCEED";
export const GET_STUDENT_PROFILE_FAIL = "GET_STUDENT_PROFILE_FAIL";

export const UPDATE_STUDENT_PROFILE = "UPDATE_STUDENT_PROFILE";
export const UPDATE_STUDENT_PROFILE_SUCCEED = "UPDATE_STUDENT_PROFILE_SUCCEED";
export const UPDATE_STUDENT_PROFILE_FAIL = "UPDATE_STUDENT_PROFILE_FAIL";

export const UPDATE_PARENT_AVATAR = "UPDATE_PARENT_AVATAR";
export const UPDATE_PARENT_AVATAR_SUCCEED = "UPDATE_PARENT_AVATAR_SUCCEED";
export const UPDATE_PARENT_AVATAR_FAIL = "UPDATE_PARENT_AVATAR_FAIL";

export const UPDATE_STUDENT_AVATAR = "UPDATE_STUDENT_AVATAR";
export const UPDATE_STUDENT_AVATAR_SUCCEED = "UPDATE_STUDENT_AVATAR_SUCCEED";
export const UPDATE_STUDENT_AVATAR_FAIL = "UPDATE_STUDENT_AVATAR_FAIL";

export const GET_STICKER = "GET_STICKER";
export const GET_STICKER_SUCCEED = "GET_STICKER_SUCCEED";
export const GET_STICKER_FAIL = "GET_STICKER_FAIL";

export const UPDATE_PARENT_AVATAR_STICKER = "UPDATE_PARENT_AVATAR_STICKER";
export const UPDATE_PARENT_AVATAR_STICKER_SUCCEED =
  "UPDATE_PARENT_AVATAR_STICKER_SUCCEED";
export const UPDATE_PARENT_AVATAR_STICKER_FAIL =
  "UPDATE_PARENT_AVATAR_STICKER_FAIL";

export const UPDATE_STUDENT_AVATAR_STICKER = "UPDATE_STUDENT_AVATAR_STICKER";
export const UPDATE_STUDENT_AVATAR_STICKER_SUCCEED =
  "UPDATE_STUDENT_AVATAR_STICKER_SUCCEED";
export const UPDATE_STUDENT_AVATAR_STICKER_FAIL =
  "UPDATE_STUDENT_AVATAR_STICKER_FAIL";

export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_SUCCEED = "GET_STUDENTS_SUCCEED";
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL";

export const GET_SCHEDULES = "GET_SCHEDULES";
export const GET_SCHEDULES_SUCCEED = "GET_SCHEDULES_SUCCEED";
export const GET_SCHEDULES_FAIL = "GET_SCHEDULES_FAIL";

export const GET_SCHEDULES_UPCOMMING = "GET_SCHEDULES_UPCOMMING";
export const GET_SCHEDULES_UPCOMMING_SUCCEED =
  "GET_SCHEDULES_UPCOMMING_SUCCEED";
export const GET_SCHEDULES_UPCOMMING_FAIL = "GET_SCHEDULES_UPCOMMING_FAIL";

export const GET_TEACHERS_PROFILE = "GET_TEACHERS_PROFILE";
export const GET_TEACHERS_PROFILE_SUCCEED = "GET_TEACHERS_PROFILE_SUCCEED";
export const GET_TEACHERS_PROFILE_FAIL = "GET_TEACHERS_PROFILE_FAIL";

export const GET_SCHEDULES_PARENT_UPCOMMING = "GET_SCHEDULES_PARENT_UPCOMMING";
export const GET_SCHEDULES_PARENT_UPCOMMING_SUCCEED =
  "GET_SCHEDULES_PARENT_UPCOMMING_SUCCEED";
export const GET_SCHEDULES_PARENT_UPCOMMING_FAIL =
  "GET_SCHEDULES_PARENT_UPCOMMING_FAIL";

export const GET_SCHEDULES_PARENT = "GET_SCHEDULES_PARENT";
export const GET_SCHEDULES_PARENT_SUCCEED = "GET_SCHEDULES_PARENT_SUCCEED";
export const GET_SCHEDULES_PARENT_FAIL = "GET_SCHEDULES_PARENT_FAIL";

export const UPDATE_PARENT_DATE_SCHEDULE = "UPDATE_PARENT_DATE_SCHEDULE";

export const UPDATE_TEACHER_DATE_SCHEDULE = "UPDATE_TEACHER_DATE_SCHEDULE";

export const UPDATE_TEACHER_DATE_SCHEDULE_SELECTED =
  "UPDATE_TEACHER_DATE_SCHEDULE_SELECTED";

export const UPDATE_PARENT_DATE_SCHEDULE_SELECTED =
  "UPDATE_PARENT_DATE_SCHEDULE_SELECTED";

export const HELP_REQUEST = "HELP_REQUEST";
export const HELP_SUCCEED = "HELP_SUCCEED";
export const HELP_FAIL = "HELP_FAIL";

export const CONNECT_STRIPE_TEACHER_REQUEST = "CONNECT_STRIPE_TEACHER_REQUEST";
export const CONNECT_STRIPE_TEACHER_SUCCEED = "CONNECT_STRIPE_TEACHER_SUCCEED";
export const CONNECT_STRIPE_TEACHER_FAIL = "CONNECT_STRIPE_TEACHER_FAIL";

export const GET_STRIPE_TEACHER_REQUEST = "GET_STRIPE_TEACHER_REQUEST";
export const GET_STRIPE_TEACHER_SUCCEED = "GET_STRIPE_TEACHER_SUCCEED";
export const GET_STRIPE_TEACHER_FAIL = "GET_STRIPE_TEACHER_FAIL";

export const GET_INIT_BOOKINGS = "GET_INIT_BOOKINGS";
export const GET_INIT_BOOKINGS_SUCCEED = "GET_INIT_BOOKINGS_SUCCEED";
export const GET_INIT_BOOKINGS_FAIL = "GET_INIT_BOOKINGS_FAIL";
export const RESET_INIT_BOOKINGS = "RESET_INIT_BOOKINGS";

export const UPDATE_BOOK_LESSON = "UPDATE_BOOK_LESSON";

export const GET_BOOKING_STUDENT = "GET_BOOKING_STUDENT";
export const GET_BOOKING_STUDENT_SUCCEED = "GET_BOOKING_STUDENT_SUCCEED";
export const GET_BOOKING_STUDENT_FAIL = "GET_BOOKING_STUDENT_FAIL";

export const CREATE_LESSON = "CREATE_LESSON";
export const CREATE_LESSON_SUCCEED = "CREATE_LESSON_SUCCEED";
export const CREATE_LESSON_FAIL = "CREATE_LESSON_FAIL";

export const GET_CARD_SETUP = "GET_CARD_SETUP";
export const GET_CARD_SETUP_SUCCEED = "GET_CARD_SETUP_SUCCEED";
export const GET_CARD_SETUP_FAIL = "GET_CARD_SETUP_FAIL";

export const GET_CARD_INFO = "GET_CARD_INFO";
export const GET_CARD_INFO_SUCCEED = "GET_CARD_INFO_SUCCEED";
export const GET_CARD_INFO_FAIL = "GET_CARD_INFO_FAIL";

export const POST_CARD_SAVE = "POST_CARD_SAVE";
export const POST_CARD_SAVE_SUCCEED = "POST_CARD_SAVE_SUCCEED";
export const POST_CARD_SAVE_FAIL = "POST_CARD_SAVE_FAIL";
export const RESET_CARD_SAVE_SUCCEED = "RESET_CARD_SAVE_SUCCEED";

export const GET_SETUP_BOOKING = "GET_SETUP_BOOKING";
export const GET_SETUP_BOOKING_SUCCEED = "GET_SETUP_BOOKING_SUCCEED";
export const GET_SETUP_BOOKING_FAIL = "GET_SETUP_BOOKING_FAIL";

export const CREATE_MAKEUP_SCHEDULE = "CREATE_MAKEUP_SCHEDULE";
export const CREATE_MAKEUP_SCHEDULE_SUCCEED = "CREATE_MAKEUP_SCHEDULE_SUCCEED";
export const CREATE_MAKEUP_SCHEDULE_FAIL = "CREATE_MAKEUP_SCHEDULE_FAIL";

export const CANCEL_LESSON_SCHEDULE = "CANCEL_LESSON_SCHEDULE";
export const CANCEL_LESSON_SCHEDULE_SUCCEED = "CANCEL_LESSON_SCHEDULE_SUCCEED";
export const CANCEL_LESSON_SCHEDULE_FAIL = "CANCEL_LESSON_SCHEDULE_FAIL";

export const REPORT_PROBLEM = "REPORT_PROBLEM";
export const REPORT_PROBLEM_SUCCEED = "REPORT_PROBLEM_SUCCEED";
export const REPORT_PROBLEM_FAIL = "REPORT_PROBLEM_FAIL";

export const CANCEL_LESSON_SCHEDULE_FOR_PARENT =
  "CANCEL_LESSON_SCHEDULE_FOR_PARENT";
export const CANCEL_LESSON_SCHEDULE_FOR_PARENT_SUCCEED =
  "CANCEL_LESSON_SCHEDULE_FOR_PARENT_SUCCEED";
export const CANCEL_LESSON_SCHEDULE_FOR_PARENT_FAIL =
  "CANCEL_LESSON_SCHEDULE_FOR_PARENT_FAIL";

export const PROGRESS_REPORT_TEACHER = "PROGRESS_REPORT_TEACHER";
export const PROGRESS_REPORT_TEACHER_SUCCEED =
  "PROGRESS_REPORT_TEACHER_SUCCEED";
export const PROGRESS_REPORT_TEACHER_FAIL = "PROGRESS_REPORT_TEACHER_FAIL";

export const GET_STUDENT_PROGRESS_REPORT = "GET_STUDENT_PROGRESS_REPORT";
export const GET_STUDENT_PROGRESS_REPORT_SUCCEED =
  "GET_STUDENT_PROGRESS_REPORT_SUCCEED";
export const GET_STUDENT_PROGRESS_REPORT_FAIL =
  "GET_STUDENT_PROGRESS_REPORT_FAIL";

export const GET_PROGRESS_REPORT_ITEM_FOR_TEACHER =
  "GET_PROGRESS_REPORT_ITEM_FOR_TEACHER";
export const GET_PROGRESS_REPORT_ITEM_FOR_TEACHER_SUCCEED =
  "GET_PROGRESS_REPORT_ITEM_FOR_TEACHER_SUCCEED";
export const GET_PROGRESS_REPORT_ITEM_FOR_TEACHER_FAIL =
  "GET_PROGRESS_REPORT_ITEM_FOR_TEACHER_FAIL";

export const GET_PROGRESS_REPORT_PARENT = "GET_PROGRESS_REPORT_PARENT";
export const GET_PROGRESS_REPORT_PARENT_SUCCEED =
  "GET_PROGRESS_REPORT_PARENT_SUCCEED";
export const GET_PROGRESS_REPORT_PARENT_FAIL =
  "GET_PROGRESS_REPORT_PARENT_FAIL";

export const GET_STUDENT_PROGRESS_REPORT_FOR_PARENT =
  "GET_STUDENT_PROGRESS_REPORT_FOR_PARENT";
export const GET_STUDENT_PROGRESS_REPORT_FOR_PARENT_SUCCEED =
  "GET_STUDENT_PROGRESS_REPORT_FOR_PARENT_SUCCEED";
export const GET_STUDENT_PROGRESS_REPORT_FOR_PARENT_FAIL =
  "GET_STUDENT_PROGRESS_REPORT_FOR_PARENT_FAIL";

export const GET_PROGRESS_REPORT_ITEM_FOR_PARENT =
  "GET_PROGRESS_REPORT_ITEM_FOR_PARENT";
export const GET_PROGRESS_REPORT_ITEM_FOR_PARENT_SUCCEED =
  "GET_PROGRESS_REPORT_ITEM_FOR_PARENT_SUCCEED";
export const GET_PROGRESS_REPORT_ITEM_FOR_PARENT_FAIL =
  "GET_PROGRESS_REPORT_ITEM_FOR_PARENT_FAIL";

export const GET_EARNING_CURRENT_DETAILS = "GET_EARNING_CURRENT_DETAILS";
export const GET_EARNING_CURRENT_DETAILS_SUCCEED =
  "GET_EARNING_CURRENT_DETAILS_SUCCEED";
export const GET_EARNING_CURRENT_DETAILS_FAIL =
  "GET_EARNING_CURRENT_DETAILS_FAIL";

export const UPDATE_TEACHER_DATE_EARNING = "UPDATE_TEACHER_DATE_EARNING";

export const GET_TEACHER_EARNINGS = "GET_TEACHER_EARNINGS";
export const GET_TEACHER_EARNINGS_SUCCEED = "GET_TEACHER_EARNINGS_SUCCEED";
export const GET_TEACHER_EARNINGS_FAIL = "GET_TEACHER_EARNINGS_FAIL";

export const UPDATE_TEACHER_DATE_EARNING_RECEIPTS =
  "UPDATE_TEACHER_DATE_EARNING_RECEIPTS";

export const GET_TEACHER_EARNINGS_RECEIPTS = "GET_TEACHER_EARNINGS_RECEIPTS";
export const GET_TEACHER_EARNINGS_RECEIPTS_SUCCEED =
  "GET_TEACHER_EARNINGS_RECEIPTS_SUCCEED";
export const GET_TEACHER_EARNINGS_RECEIPTS_FAIL =
  "GET_TEACHER_EARNINGS_RECEIPTS_FAIL";

export const UPDATE_PARENT_DATE_PAYMENTS_INVOICES =
  "UPDATE_PARENT_DATE_PAYMENTS_INVOICES";

export const GET_PARENT_PAYMENTS_INVOICES = "GET_PARENT_PAYMENTS_INVOICES";
export const GET_PARENT_PAYMENTS_INVOICES_SUCCEED =
  "GET_PARENT_PAYMENTS_INVOICES_SUCCEED";
export const GET_PARENT_PAYMENTS_INVOICES_FAIL =
  "GET_PARENT_PAYMENTS_INVOICES_FAIL";

export const SET_NEW_DATA_TEACHERS = "SET_NEW_DATA_TEACHERS";

export const GET_ZOOM_AUTH_CODE = "GET_ZOOM_AUTH_CODE";
export const GET_ZOOM_AUTH_CODE_SUCCEED = "GET_ZOOM_AUTH_CODE_SUCCEED";
export const GET_ZOOM_AUTH_CODE_FAIL = "GET_ZOOM_AUTH_CODE_FAIL";

export const SET_HEIGHT_HEADER = "SET_HEIGHT_HEADER";
export const SET_TOP_HEADER = "SET_TOP_HEADER";
export const SET_SIZE_TEACHERS_FILTER = "SET_SIZE_TEACHERS_FILTER";

export const SET_OPEN_MODAL_JOIN_HOMEMUSE = "SET_OPEN_MODAL_JOIN_HOMEMUSE";

export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS";
export const GET_ALL_TEACHERS_SUCCEED = "GET_ALL_TEACHERS_SUCCEED";
export const GET_ALL_TEACHERS_FAIL = "GET_ALL_TEACHERS_FAIL";

export const GET_REVIEW = "GET_REVIEW";
export const GET_REVIEW_SUCCEED = "GET_REVIEW_SUCCEED";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";
